semana-0/sobre-mim/minha-bio.txt
=> adicionei  bio

semana1/operadores/.vscode/settings.json, semana1/operadores/index.html, semana1/operadores/index.js
=> semana1-aula04

semana1/semana1-aula5/strings-arrays/.vscode/settings.json, semana1/semana1-aula5/strings-arrays/index.html, semana1/semana1-aula5/strings-arrays/index.js
=> semana1 aula 05

.gitignore, semana2-cond/condicionais/index.html, semana2-cond/condicionais/index.js
=> semana 2 aula condicionais

semana2/semana2-lacos/.vscode/settings.json, semana2/semana2-lacos/index.html, semana2/semana2-lacos/index.js
=> Semana2 lacos

semana2/aula10-map-filter/index.html, semana2/aula10-map-filter/index.js
=> semana 2 aula 10

semana2/blackjack/index.html, semana2/blackjack/nossoJogo.js
=> Semana2 projeto

react/boiler-plate/package-lock.json, react/boiler-plate/package.json, react/boiler-plate/public/index.html, react/boiler-plate/public/manifest.json, react/boiler-plate/src/App.js, react/boiler-plate/src/index.js, react/boiler-plate/src/styles.css
Todos os requisitos estão funcionando
Tudo está funcionando
protective-spark.surge.sh
=> lista de tarefas

postman/labefy.postman_collection (1).json
=> Postman Labefy

template-express/package-lock.json, template-express/package.json, template-express/src/data.ts, template-express/src/index.ts, template-express/src/types.ts, template-express/tsconfig.json
=> trabalho aula 43

typescript/src/index.ts, typescript/tsconfig.json
=> primeira aula typescript

node/primeiro-trab/exercicio1.js, node/primeiro-trab/exercicio2.js, node/primeiro-trab/exercicio3.js, node/primeiro-trab/index.js, node/primeiro-trab/package.json
=> primeira aula node

mysql/sql.md
=> primeiro teste mysql

mysql2/aula46.md
=> aprofundamento sql

projeto-sql/knex/package.json, projeto-sql/knex/src/app.ts, projeto-sql/knex/src/connection.ts, projeto-sql/knex/src/index.ts, projeto-sql/knex/tsconfig.json
=> projeto to do list

jest/testes/.gitignore, jest/testes/jest.config.js, jest/testes/package-lock.json, jest/testes/package.json, jest/testes/src/business/UserBusiness.ts, jest/testes/src/controller/UserController.ts, jest/testes/src/data/BaseDatabase.ts, jest/testes/src/data/UserDatabase.ts, jest/testes/src/errors/CustomError.ts, jest/testes/src/index.ts, jest/testes/src/model/User.ts, jest/testes/src/router/UserRouter.ts, jest/testes/src/services/hashGenerator.ts, jest/testes/src/services/idGenerator.ts, jest/testes/src/services/tokenGenerator.ts, jest/testes/tests/UserBussines.test.ts, jest/testes/tests/mocks/UserDatabaseMock.ts, jest/testes/tests/mocks/hashGeneratorMock.ts, jest/testes/tests/mocks/idGeneratorMock.ts, jest/testes/tests/mocks/tokenGeneratorMock.ts, jest/testes/tests/mocks/userMock.ts, jest/testes/tsconfig.json, labook/labook/package-lock.json
=> testes backend

jest/jest2/exercício.md, jest/jest2/jest.config.js, jest/jest2/package-lock.json, jest/jest2/package.json, jest/jest2/src/exercicio1.ts
=> segundo dia de testes

jest/jest/exercicio.md, jest/jest/jest.config.js, jest/jest/package-lock.json, jest/jest/package.json, jest/jest/tsconfig.json
=> jest testes

labook/labook/.gitignore, labook/labook/README.md, labook/labook/package.json, labook/labook/src/data/BaseDatabase.ts, labook/labook/src/index.ts, labook/labook/src/migrations.ts, labook/labook/tsconfig.json
=> labook inicial

arquitetura/template/.gitignore, arquitetura/template/README.md, arquitetura/template/package.json, arquitetura/template/src/index.ts, arquitetura/template/src/services/authenticator.ts, arquitetura/template/src/services/hashManager.ts, arquitetura/template/src/services/idGenerator.ts, arquitetura/template/tsconfig.json
=> arquitetura inicial

back/projeto-labcommerce/package-lock.json, back/projeto-labcommerce/package.json, back/projeto-labcommerce/src/index.ts, back/projeto-labcommerce/tsconfig.json, projeto-sql/knex/package.json, projeto-sql/knex/src/app.ts, projeto-sql/knex/src/connection.ts, projeto-sql/knex/src/index.ts, projeto-sql/knex/tsconfig.json
=> Labcommerce
